export const videos = {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/6EdKBYkB1ssgGjc249ud1L55o8d.jpg",
        genre_ids: [28, 878, 53],
        id: 848278,
        original_language: "en",
        original_title: "Jurassic Hunt",
        overview:
          "Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!",
        popularity: 4475.053,
        poster_path: "/Czhr00kB8awffakEcQS5ON1ELm.jpg",
        release_date: "2021-08-23",
        title: "Jurassic Hunt",
        video: false,
        vote_average: 4.7,
        vote_count: 50,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit',
        
      },
     
      {
        adult: false,
        backdrop_path: "/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg",
        genre_ids: [28, 12, 53, 878],
        id: 497698,
        original_language: "en",
        original_title: "Black Widow",
        overview:
          "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
        popularity: 2110.202,
        poster_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
        release_date: "2021-07-07",
        title: "Black Widow",
        video: false,
        vote_average: 7.8,
        vote_count: 4925,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit'
      },
      {
        adult: false,
        backdrop_path: "/nprqOIEfiMMQx16lgKeLf3rmPrR.jpg",
        genre_ids: [28, 53, 18],
        id: 619297,
        original_language: "en",
        original_title: "Sweet Girl",
        overview:
          "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
        popularity: 2090.347,
        poster_path: "/cP7odDzzFBD9ycxj2laTeFWGLjD.jpg",
        release_date: "2021-08-18",
        title: "Sweet Girl",
        video: false,
        vote_average: 6.9,
        vote_count: 511,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit'
      },
      
      {
        adult: false,
        backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
        genre_ids: [28, 80, 53],
        id: 385128,
        original_language: "en",
        original_title: "F9",
        overview:
          "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
        popularity: 1648.35,
        poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
        release_date: "2021-05-19",
        title: "F9",
        video: false,
        vote_average: 7.5,
        vote_count: 3555,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit'
      },
      {
        adult: false,
        backdrop_path: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
        genre_ids: [878, 28, 53],
        id: 581726,
        original_language: "en",
        original_title: "Infinite",
        overview:
          "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
        popularity: 1557.1,
        poster_path: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
        release_date: "2021-06-10",
        title: "Infinite",
        video: false,
        vote_average: 7.4,
        vote_count: 1009,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit'
      },
      {
        adult: false,
        backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
        genre_ids: [16, 35, 10751, 14],
        id: 508943,
        original_language: "en",
        original_title: "Luca",
        overview:
          "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
        popularity: 1480.653,
        poster_path: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
        release_date: "2021-06-17",
        title: "Luca",
        video: false,
        vote_average: 8.1,
        vote_count: 4416,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit'
      },
      {
        adult: false,
        backdrop_path: "/qD45xHA35HdJDGOaA1AgDwiWEgO.jpg",
        genre_ids: [10749, 18],
        id: 744275,
        original_language: "en",
        original_title: "After We Fell",
        overview:
          "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
        popularity: 1232.869,
        poster_path: "/oOZITZodAja6optBgLh8ZZrgzbb.jpg",
        release_date: "2021-09-01",
        title: "After We Fell",
        video: false,
        vote_average: 8.5,
        vote_count: 212,
        video_url:'https://www.youtube.com/watch?v=2F8zBNzmROM&t=6s&ab_channel=BhaveshPurohit'
      },
    ],
    total_pages: 500,
    total_results: 10000,
  };